---
api_key:
  description: "The API key for OpsGenie."
  type: "string"
  secret: true
  required: true
region:
  description: >-
    The service region for your OpsGenie account - check the
    OpsGenie documentation for the complete list of API regions
  type: "string"
  required: false
  default: "us"
